version: '3'

services:

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    

  db:
    image: postgres
    environment:
      POSTGRES_DB : FlightVoyage
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : postgres@123
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5  
    
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgresadmin@1234
    ports:
      - "5050:80"
    depends_on:
      - db
    
volumes:
  postgres_data: