# Generated by Django 5.0.2 on 2024-02-28 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('number', models.CharField(unique=True)),
                ('departure_date', models.DateField()),
                ('departure_tiime', models.TimeField()),
                ('seats', models.IntegerField()),
                ('country', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_flights', to='flights.country')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_flights', to='flights.country')),
            ],
        ),
    ]
