# Generated by Django 5.0.2 on 2024-02-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_destination_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destination_id',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='source_id',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
