# Generated by Django 5.0.2 on 2024-02-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_rename_destination_id_flight_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='country',
        ),
    ]
