# Generated by Django 5.0.2 on 2024-02-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_bookinglog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='departure_tiime',
            new_name='departure_time',
        ),
    ]
