# Generated by Django 5.0.2 on 2024-02-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_rename_departure_tiime_flight_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinglog',
            name='booking_status',
            field=models.IntegerField(default=0),
        ),
    ]
