# Generated by Django 5.0.2 on 2024-03-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_alter_flightseatmanager_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflightlog',
            name='cancellation_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userflightlog',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Cancelled'), (0, 'Pending'), (1, 'Confirmed')], default=0),
        ),
    ]
