# Generated by Django 5.0.2 on 2024-03-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0017_alter_flight_seats_alter_flightbookinglog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightseatmanager',
            name='is_changed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flightseatmanager',
            name='remarks',
            field=models.CharField(blank=True, null=True),
        ),
    ]
