# Generated by Django 5.0.2 on 2024-03-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='cancellation_period',
        ),
    ]
