# Generated by Django 5.0.2 on 2024-03-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userlog_seat_alter_userlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='is_changed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlog',
            name='remarks',
            field=models.CharField(blank=True, null=True),
        ),
    ]
